<a href="https://colab.research.google.com/github/prasertrak/Advanced-Data-Engineering-and-Applied-Analytics/blob/main/Part2_Pandas_and_CSV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Example 1 — Import pandas**

Concept เริ่มใช้ pandas library

In [ ]:
import pandas as pd

**Example 2 — Create Simple DataFrame**

Concept DataFrame = ตารางข้อมูล

In [ ]:
!ls

sample_data

In [ ]:
import pandas as pd

data = {
    "order_id": ["ORD001", "ORD002", "ORD003", "ORD001","ORD005"],
    "province": ["bangkok","pratumtani","nakornratchasima","bangkok","pratumtani"],
    "amount": [1000, 2000, 3000, 1000, 4000],
    "order_date": ["2023-01-01", "2023-01-02", "2023-01-03", "2023-01-01","2023-01-07"],
    "delivery_date": ["2023-01-05", "2023-01-06", "2023-01-07", "2023-01-05", "2023-01-09"],
    "status": ["processing", "shipped", "", "processing", "shipped"]
}

df = pd.DataFrame(data)

print(df)
df
df.to_csv("orders.csv", index=False)

  order_id          province  amount  order_date delivery_date      status
0   ORD001           bangkok    1000  2023-01-01    2023-01-05  processing
1   ORD002        pratumtani    2000  2023-01-02    2023-01-06     shipped
2   ORD003  nakornratchasima    3000  2023-01-03    2023-01-07
3   ORD001           bangkok    1000  2023-01-01    2023-01-05  processing
4   ORD005        pratumtani    4000  2023-01-07    2023-01-09     shipped

In [ ]:
!ls

orders.csv  sample_data

**Example 3 — Read CSV File**

Concept โหลดข้อมูลจาก CSV

CSV = source system

In [ ]:
df = pd.read_csv("orders.csv")

print(df)

  order_id          province  amount  order_date delivery_date      status
0   ORD001           bangkok    1000  2023-01-01    2023-01-05  processing
1   ORD002        pratumtani    2000  2023-01-02    2023-01-06     shipped
2   ORD003  nakornratchasima    3000  2023-01-03    2023-01-07         NaN
3   ORD001           bangkok    1000  2023-01-01    2023-01-05  processing
4   ORD005        pratumtani    4000  2023-01-07    2023-01-09     shipped

**Example 4 — View First Rows**

Concept ตรวจข้อมูลเบื้องต้น

In [ ]:
print(df.head())

  order_id          province  amount  order_date delivery_date      status
0   ORD001           bangkok    1000  2023-01-01    2023-01-05  processing
1   ORD002        pratumtani    2000  2023-01-02    2023-01-06     shipped
2   ORD003  nakornratchasima    3000  2023-01-03    2023-01-07         NaN
3   ORD001           bangkok    1000  2023-01-01    2023-01-05  processing
4   ORD005        pratumtani    4000  2023-01-07    2023-01-09     shipped

In [ ]:
df.describe()

            amount
count     5.000000
mean   2200.000000
std    1303.840481
min    1000.000000
25%    1000.000000
50%    2000.000000
75%    3000.000000
max    4000.000000

**Example 5 — Select Column**

Concept เลือก column ที่ต้องการ

In [ ]:
df

  order_id          province  amount  order_date delivery_date      status
0   ORD001           bangkok    1000  2023-01-01    2023-01-05  processing
1   ORD002        pratumtani    2000  2023-01-02    2023-01-06     shipped
2   ORD003  nakornratchasima    3000  2023-01-03    2023-01-07         NaN
3   ORD001           bangkok    1000  2023-01-01    2023-01-05  processing
4   ORD005        pratumtani    4000  2023-01-07    2023-01-09     shipped

In [ ]:
print(df["province"])

0             bangkok
1          pratumtani
2    nakornratchasima
3             bangkok
4          pratumtani
Name: province, dtype: object

In [ ]:
df

  order_id          province  amount  order_date delivery_date      status
0   ORD001           bangkok    1000  2023-01-01    2023-01-05  processing
1   ORD002        pratumtani    2000  2023-01-02    2023-01-06     shipped
2   ORD003  nakornratchasima    3000  2023-01-03    2023-01-07         NaN
3   ORD001           bangkok    1000  2023-01-01    2023-01-05  processing
4   ORD005        pratumtani    4000  2023-01-07    2023-01-09     shipped

**Example 6 — Filter Data**

Concept กรองข้อมูล

In [ ]:
high_value_orders = df[
    df["amount"] > 1000
]

print(high_value_orders)

  order_id          province  amount  order_date delivery_date   status
1   ORD002        pratumtani    2000  2023-01-02    2023-01-06  shipped
2   ORD003  nakornratchasima    3000  2023-01-03    2023-01-07      NaN
4   ORD005        pratumtani    4000  2023-01-07    2023-01-09  shipped

**Example 7 — Add New Column**

Concept สร้าง derived field

In [ ]:
df

  order_id          province  amount  order_date delivery_date      status
0   ORD001           bangkok    1000  2023-01-01    2023-01-05  processing
1   ORD002        pratumtani    2000  2023-01-02    2023-01-06     shipped
2   ORD003  nakornratchasima    3000  2023-01-03    2023-01-07         NaN
3   ORD001           bangkok    1000  2023-01-01    2023-01-05  processing
4   ORD005        pratumtani    4000  2023-01-07    2023-01-09     shipped

In [ ]:
df["vat"] = df["amount"] * 0.07

print(df)

  order_id          province  amount  order_date delivery_date      status  \
0   ORD001           bangkok    1000  2023-01-01    2023-01-05  processing
1   ORD002        pratumtani    2000  2023-01-02    2023-01-06     shipped
2   ORD003  nakornratchasima    3000  2023-01-03    2023-01-07         NaN
3   ORD001           bangkok    1000  2023-01-01    2023-01-05  processing
4   ORD005        pratumtani    4000  2023-01-07    2023-01-09     shipped

     vat
0   70.0
1  140.0
2  210.0
3   70.0
4  280.0

In [ ]:
df

,order_id,province,amount,order_date,delivery_date,status,vat
0,ORD001,bangkok,1000,2023-01-01,2023-01-05,processing,70.0
1,ORD002,pratumtani,2000,2023-01-02,2023-01-06,shipped,140.0
2,ORD003,nakornratchasima,3000,2023-01-03,2023-01-07,NaN,210.0
3,ORD001,bangkok,1000,2023-01-01,2023-01-05,processing,70.0
4,ORD005,pratumtani,4000,2023-01-07,2023-01-09,shipped,280.0

**Example 8 — Calculate Net Amount**

Concept Transformation logic

In [ ]:
df["net_amount"] = (
    df["amount"] + df["vat"]
)

print(df)

  order_id          province  amount  order_date delivery_date      status  \
0   ORD001           bangkok    1000  2023-01-01    2023-01-05  processing
1   ORD002        pratumtani    2000  2023-01-02    2023-01-06     shipped
2   ORD003  nakornratchasima    3000  2023-01-03    2023-01-07         NaN
3   ORD001           bangkok    1000  2023-01-01    2023-01-05  processing
4   ORD005        pratumtani    4000  2023-01-07    2023-01-09     shipped

     vat  net_amount
0   70.0      1070.0
1  140.0      2140.0
2  210.0      3210.0
3   70.0      1070.0
4  280.0      4280.0

In [ ]:
df

,order_id,province,amount,order_date,delivery_date,status,vat,net_amount
0,ORD001,bangkok,1000,2023-01-01,2023-01-05,processing,70.0,1070.0
1,ORD002,pratumtani,2000,2023-01-02,2023-01-06,shipped,140.0,2140.0
2,ORD003,nakornratchasima,3000,2023-01-03,2023-01-07,NaN,210.0,3210.0
3,ORD001,bangkok,1000,2023-01-01,2023-01-05,processing,70.0,1070.0
4,ORD005,pratumtani,4000,2023-01-07,2023-01-09,shipped,280.0,4280.0

**Example 9 — Handle NULL Values**

Concept Data cleaning

In [ ]:
df

,order_id,province,amount,order_date,delivery_date,status,vat,net_amount
0,ORD001,bangkok,1000,2023-01-01,2023-01-05,processing,70.0,1070.0
1,ORD002,pratumtani,2000,2023-01-02,2023-01-06,shipped,140.0,2140.0
2,ORD003,nakornratchasima,3000,2023-01-03,2023-01-07,NaN,210.0,3210.0
3,ORD001,bangkok,1000,2023-01-01,2023-01-05,processing,70.0,1070.0
4,ORD005,pratumtani,4000,2023-01-07,2023-01-09,shipped,280.0,4280.0

In [ ]:
df["status"] = df["status"].fillna(
    "UNKNOWN"
)

In [ ]:
df

,order_id,province,amount,order_date,delivery_date,status,vat,net_amount
0,ORD001,bangkok,1000,2023-01-01,2023-01-05,processing,70.0,1070.0
1,ORD002,pratumtani,2000,2023-01-02,2023-01-06,shipped,140.0,2140.0
2,ORD003,nakornratchasima,3000,2023-01-03,2023-01-07,UNKNOWN,210.0,3210.0
3,ORD001,bangkok,1000,2023-01-01,2023-01-05,processing,70.0,1070.0
4,ORD005,pratumtani,4000,2023-01-07,2023-01-09,shipped,280.0,4280.0

**Example 10 — Remove Duplicate Rows**

Concept Deduplication

In [ ]:
df = df.drop_duplicates()

df

,order_id,province,amount,order_date,delivery_date,status,vat,net_amount
0,ORD001,bangkok,1000,2023-01-01,2023-01-05,processing,70.0,1070.0
1,ORD002,pratumtani,2000,2023-01-02,2023-01-06,shipped,140.0,2140.0
2,ORD003,nakornratchasima,3000,2023-01-03,2023-01-07,UNKNOWN,210.0,3210.0
4,ORD005,pratumtani,4000,2023-01-07,2023-01-09,shipped,280.0,4280.0

**Example 11 — Standardize Text**

Concept Normalize data

In [ ]:
df

,order_id,province,amount,order_date,delivery_date,status,vat,net_amount
0,ORD001,bangkok,1000,2023-01-01,2023-01-05,processing,70.0,1070.0
1,ORD002,pratumtani,2000,2023-01-02,2023-01-06,shipped,140.0,2140.0
2,ORD003,nakornratchasima,3000,2023-01-03,2023-01-07,UNKNOWN,210.0,3210.0
4,ORD005,pratumtani,4000,2023-01-07,2023-01-09,shipped,280.0,4280.0

In [ ]:
df["province"] = (
    df["province"].str.upper()
)

df

/tmp/ipykernel_549/747764047.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["province"] = (

,order_id,province,amount,order_date,delivery_date,status,vat,net_amount
0,ORD001,BANGKOK,1000,2023-01-01,2023-01-05,processing,70.0,1070.0
1,ORD002,PRATUMTANI,2000,2023-01-02,2023-01-06,shipped,140.0,2140.0
2,ORD003,NAKORNRATCHASIMA,3000,2023-01-03,2023-01-07,UNKNOWN,210.0,3210.0
4,ORD005,PRATUMTANI,4000,2023-01-07,2023-01-09,shipped,280.0,4280.0

**Example 12 — Convert Date Format**

Concept Date handling

In [ ]:
df

,order_id,province,amount,order_date,delivery_date,status,vat,net_amount
0,ORD001,BANGKOK,1000,2023-01-01,2023-01-05,processing,70.0,1070.0
1,ORD002,PRATUMTANI,2000,2023-01-02,2023-01-06,shipped,140.0,2140.0
2,ORD003,NAKORNRATCHASIMA,3000,2023-01-03,2023-01-07,UNKNOWN,210.0,3210.0
4,ORD005,PRATUMTANI,4000,2023-01-07,2023-01-09,shipped,280.0,4280.0

In [ ]:
df["order_date"] = pd.to_datetime(
    df["order_date"]
)

df

/tmp/ipykernel_549/4208522122.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["order_date"] = pd.to_datetime(

,order_id,province,amount,order_date,delivery_date,status,vat,net_amount
0,ORD001,BANGKOK,1000,2023-01-01,2023-01-05,processing,70.0,1070.0
1,ORD002,PRATUMTANI,2000,2023-01-02,2023-01-06,shipped,140.0,2140.0
2,ORD003,NAKORNRATCHASIMA,3000,2023-01-03,2023-01-07,UNKNOWN,210.0,3210.0
4,ORD005,PRATUMTANI,4000,2023-01-07,2023-01-09,shipped,280.0,4280.0

In [ ]:
df["delivery_date"] = pd.to_datetime(
    df["delivery_date"]
)

print(df)

  order_id          province  amount order_date delivery_date      status  \
0   ORD001           BANGKOK    1000 2023-01-01    2023-01-05  processing
1   ORD002        PRATUMTANI    2000 2023-01-02    2023-01-06     shipped
2   ORD003  NAKORNRATCHASIMA    3000 2023-01-03    2023-01-07     UNKNOWN
4   ORD005        PRATUMTANI    4000 2023-01-07    2023-01-09     shipped

     vat  net_amount
0   70.0      1070.0
1  140.0      2140.0
2  210.0      3210.0
4  280.0      4280.0

/tmp/ipykernel_549/16542349.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["delivery_date"] = pd.to_datetime(

**Example 13 — Calculate Delivery Days**

Concept Business KPI

delivery_days = operational KPI

In [ ]:
df

,order_id,province,amount,order_date,delivery_date,status,vat,net_amount
0,ORD001,BANGKOK,1000,2023-01-01,2023-01-05,processing,70.0,1070.0
1,ORD002,PRATUMTANI,2000,2023-01-02,2023-01-06,shipped,140.0,2140.0
2,ORD003,NAKORNRATCHASIMA,3000,2023-01-03,2023-01-07,UNKNOWN,210.0,3210.0
4,ORD005,PRATUMTANI,4000,2023-01-07,2023-01-09,shipped,280.0,4280.0

In [ ]:
df["delivery_days"] = (
    df["delivery_date"]
    - df["order_date"]
)

print(df)

  order_id          province  amount order_date delivery_date      status  \
0   ORD001           BANGKOK    1000 2023-01-01    2023-01-05  processing
1   ORD002        PRATUMTANI    2000 2023-01-02    2023-01-06     shipped
2   ORD003  NAKORNRATCHASIMA    3000 2023-01-03    2023-01-07     UNKNOWN
4   ORD005        PRATUMTANI    4000 2023-01-07    2023-01-09     shipped

     vat  net_amount delivery_days
0   70.0      1070.0        4 days
1  140.0      2140.0        4 days
2  210.0      3210.0        4 days
4  280.0      4280.0        2 days

/tmp/ipykernel_549/826004615.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["delivery_days"] = (

In [ ]:
df["delivery_days"] = (
    df["delivery_date"]
    - df["order_date"]
).dt.days

print(df)

  order_id          province  amount order_date delivery_date      status  \
0   ORD001           BANGKOK    1000 2023-01-01    2023-01-05  processing
1   ORD002        PRATUMTANI    2000 2023-01-02    2023-01-06     shipped
2   ORD003  NAKORNRATCHASIMA    3000 2023-01-03    2023-01-07     UNKNOWN
4   ORD005        PRATUMTANI    4000 2023-01-07    2023-01-09     shipped

     vat  net_amount  delivery_days
0   70.0      1070.0              4
1  140.0      2140.0              4
2  210.0      3210.0              4
4  280.0      4280.0              2

/tmp/ipykernel_549/2377843617.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["delivery_days"] = (

In [ ]:
df

,order_id,province,amount,order_date,delivery_date,status,vat,net_amount,delivery_days
0,ORD001,BANGKOK,1000,2023-01-01,2023-01-05,processing,70.0,1070.0,4
1,ORD002,PRATUMTANI,2000,2023-01-02,2023-01-06,shipped,140.0,2140.0,4
2,ORD003,NAKORNRATCHASIMA,3000,2023-01-03,2023-01-07,UNKNOWN,210.0,3210.0,4
4,ORD005,PRATUMTANI,4000,2023-01-07,2023-01-09,shipped,280.0,4280.0,2

**Example 14 — Group By**

Concept Aggregation

In [ ]:
df

,order_id,province,amount,order_date,delivery_date,status,vat,net_amount,delivery_days
0,ORD001,BANGKOK,1000,2023-01-01,2023-01-05,processing,70.0,1070.0,4
1,ORD002,PRATUMTANI,2000,2023-01-02,2023-01-06,shipped,140.0,2140.0,4
2,ORD003,NAKORNRATCHASIMA,3000,2023-01-03,2023-01-07,UNKNOWN,210.0,3210.0,4
4,ORD005,PRATUMTANI,4000,2023-01-07,2023-01-09,shipped,280.0,4280.0,2

In [ ]:
summary = df.groupby(
    "province"
)["amount"].sum()

print(summary)
summary

province
BANGKOK             1000
NAKORNRATCHASIMA    3000
PRATUMTANI          6000
Name: amount, dtype: int64

province
BANGKOK             1000
NAKORNRATCHASIMA    3000
PRATUMTANI          6000
Name: amount, dtype: int64

**Example 15 — Sort Data**

Concept Ranking

In [ ]:
df

,order_id,province,amount,order_date,delivery_date,status,vat,net_amount,delivery_days
0,ORD001,BANGKOK,1000,2023-01-01,2023-01-05,processing,70.0,1070.0,4
1,ORD002,PRATUMTANI,2000,2023-01-02,2023-01-06,shipped,140.0,2140.0,4
2,ORD003,NAKORNRATCHASIMA,3000,2023-01-03,2023-01-07,UNKNOWN,210.0,3210.0,4
4,ORD005,PRATUMTANI,4000,2023-01-07,2023-01-09,shipped,280.0,4280.0,2

In [ ]:
sorted_df = df.sort_values(
    by="amount",
    ascending=False
)

print(sorted_df)
sorted_df

  order_id          province  amount order_date delivery_date      status  \
4   ORD005        PRATUMTANI    4000 2023-01-07    2023-01-09     shipped
2   ORD003  NAKORNRATCHASIMA    3000 2023-01-03    2023-01-07     UNKNOWN
1   ORD002        PRATUMTANI    2000 2023-01-02    2023-01-06     shipped
0   ORD001           BANGKOK    1000 2023-01-01    2023-01-05  processing

     vat  net_amount  delivery_days
4  280.0      4280.0              2
2  210.0      3210.0              4
1  140.0      2140.0              4
0   70.0      1070.0              4

,order_id,province,amount,order_date,delivery_date,status,vat,net_amount,delivery_days
4,ORD005,PRATUMTANI,4000,2023-01-07,2023-01-09,shipped,280.0,4280.0,2
2,ORD003,NAKORNRATCHASIMA,3000,2023-01-03,2023-01-07,UNKNOWN,210.0,3210.0,4
1,ORD002,PRATUMTANI,2000,2023-01-02,2023-01-06,shipped,140.0,2140.0,4
0,ORD001,BANGKOK,1000,2023-01-01,2023-01-05,processing,70.0,1070.0,4

**Example 16 — Export CSV**

Concept ส่ง output ออกไป

In [ ]:
df.to_csv(
    "clean_orders.csv",
    index=False # ไม่ต้องใส่เลขบรรทัด ที่เป็น auto-generated มาด้วย
)

In [ ]:
!ls

clean_orders.csv  orders.csv  sample_data

**Example 17 — Simple Validation**

Concept Data quality check

In [ ]:
df

,order_id,province,amount,order_date,delivery_date,status,vat,net_amount,delivery_days
0,ORD001,BANGKOK,1000,2023-01-01,2023-01-05,processing,70.0,1070.0,4
1,ORD002,PRATUMTANI,2000,2023-01-02,2023-01-06,shipped,140.0,2140.0,4
2,ORD003,NAKORNRATCHASIMA,3000,2023-01-03,2023-01-07,UNKNOWN,210.0,3210.0,4
4,ORD005,PRATUMTANI,4000,2023-01-07,2023-01-09,shipped,280.0,4280.0,2

In [ ]:
invalid_orders = df[
    df["amount"] < 0
]

print(invalid_orders)

Empty DataFrame
Columns: [order_id, province, amount, order_date, delivery_date, status, vat, net_amount, delivery_days]
Index: []

**Example 18 — Full Mini Pipeline**

Concept End-to-End Data Flow

In [ ]:
import pandas as pd

# read source data
df = pd.read_csv("orders.csv")

# clean province
df["province"] = (
    df["province"].str.upper()
)

# fill null status
df["status"] = df["status"].fillna(
    "UNKNOWN"
)

# calculate VAT
df["vat"] = df["amount"] * 0.07

# export output
df.to_csv(
    "processed_orders.csv",
    index=False
)

print(df)
print("Pipeline Completed")

  order_id          province  amount  order_date delivery_date      status  \
0   ORD001           BANGKOK    1000  2023-01-01    2023-01-05  processing
1   ORD002        PRATUMTANI    2000  2023-01-02    2023-01-06     shipped
2   ORD003  NAKORNRATCHASIMA    3000  2023-01-03    2023-01-07     UNKNOWN
3   ORD001           BANGKOK    1000  2023-01-01    2023-01-05  processing
4   ORD005        PRATUMTANI    4000  2023-01-07    2023-01-09     shipped

     vat
0   70.0
1  140.0
2  210.0
3   70.0
4  280.0
Pipeline Completed

In [ ]:
!ls

clean_orders.csv  orders.csv  processed_orders.csv  sample_data